export const FORM_ERROR_STATUS = 'FORM_ERROR'
export const FORM_PROGRESS_STATUS = 'FORM_INPROGRESS'
export const FORM_SUBMIT_STATUS = 'FORM_SUBMIT'
export const FORM_ACTION_ERROR_STATUS = 'FORM_ACTION_ERROR'
